### ISSUE TITLE
feature/create_user_authentication_ui

### ISSUE THREAD

**Issue by CNwante** [Wikki2000/WIS-Grader#3]
**Description:**
Design and Implement User Authentication UI.

**Tasks:**

- [ ] Create Registration Page
- [ ] Create Verification Page
- [ ] Create Login-Page
- [ ] Create Verification success page
- [ ] Create Password recovery page
